# Generated by Django 4.2.1 on 2023-06-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_product_parent_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TE', 'Чай'), ('BL', 'Чёрный чай'), ('GR', 'Зелёный чай'), ('FR', 'Фруктовый'), ('CF', 'Кофе'), ('KN', 'Кофе Кения'), ('BR', 'Кофе Бразилия'), ('VT', 'Кофе Вьетнам'), ('SP', 'Сиропы'), ('FR', 'Фруктовые сиропы'), ('AL', 'Алкогольные сиропы')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='parent_category',
            field=models.CharField(choices=[('TE', 'Чай'), ('BL', 'Чёрный чай'), ('GR', 'Зелёный чай'), ('FR', 'Фруктовый'), ('CF', 'Кофе'), ('KN', 'Кофе Кения'), ('BR', 'Кофе Бразилия'), ('VT', 'Кофе Вьетнам'), ('SP', 'Сиропы'), ('FR', 'Фруктовые сиропы'), ('AL', 'Алкогольные сиропы')], default='', max_length=2),
        ),
    ]
